### ISSUE TITLE
本人的开源贡献，不知是否有机会合并贡献到上游

### ISSUE THREAD

**Issue by ghost** [umeng/mvn-repo-umeng#12]
PHP方面
整理并优化了PHP SDK
https://github.com/netroby/umeng-php-sdk
Java方面

发布了umeng push sdk 到jcenter上面， 添加Gradle编译支持
https://bintray.com/bintray/jcenter?filterByPkgName=umeng-push-sdk-java
源代码位于
https://github.com/netroby/umeng-push-java-sdk
Demo位于
https://github.com/netroby/umeng-push-java-demo

**Comment by hehonghui** [comment]
建议发一个pull request

**Comment by ghost** [comment]
PHPSDK 贵司没有在git上发布仓库。
Java SDK的仓库是哪个？
看到了Maven的仓库，因此如果要支持Gradle，应该要切一个分支，或者新起一个仓库。

所以不能直接发PR。
PR只能针对当前已经有的仓库
